name: JDDock

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: List files and create directories
        run: |
          pwd && ls && mkdir -p downloads
          ls
      - name: Run Docker Container
        run: |
          docker run -d \
            -e JD_DEVICENAME="${{ secrets.JD_DEVICENAME }}" \
            -e JD_EMAIL="${{ secrets.JD_EMAIL }}" \
            -e JD_PASSWORD="${{ secrets.JD_PASSWORD }}" \
            -v "$(pwd)/downloads:/jdownloader/downloads" \
             antlafarge/jdownloader:ubuntu
      - name: Download and install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          wget -qq ${{ secrets.CONFIG }}
      - name: Running Script
        run: bash start.sh
      - name: Stop Docker Container
        run: docker stop $(docker ps -q --filter ancestor=jddoc)
